accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signupaccount/', views.signupaccount, name='signupaccount'),
    path('logout/', views.logoutaccount, name='logoutaccount'),
    path('login/', views.loginaccount, name='loginaccount'),
]

jobhunt/urls.py
from django.urls import path
from . import views

app_name = 'jobhunt'

urlpatterns = [
    path('', views.job_list, name='job_list'),
    path('detail/<int:job_id>', views.job_detail, name='job_detail'),
    path('detail/<int:job_id>/create/', views.add_contact, name="add_contact"),
    path('detail/<int:job_id>/add/', views.add_activity, name="add_activity"),
    path('detail/add/',views.add_job, name='add_job'),
]

jobhuntpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobhunt.urls', namespace='jobhunt')),
    path('accounts/', include('accounts.urls')),
]

jobhuntpro/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/jobhunt.css' %}">    
<head>
    <nav class="navbar navbar-expand-lg navbar-light bg-honeydew mb-3">
        <div class="container">
            <a class="navbar-brand" href="{% url 'jobhunt:job_list' %}">
            <img src="{% static 'jobhunt.png' %}" alt="" width="30" height="24"
                class="d-inline-block align-text-top" />
            Job Hunt Pro
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <p class='nav-link'>Welcome, {{ user.username }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
                    <a class="nav-link" href="{% url 'accounts:logoutaccount' %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'accounts:loginaccount' %}">Login</a>
                    <a class="nav-link" href="{% url 'accounts:signupaccount' %}">Sign Up</a>
                {% endif %}
            </div>
            </div>
        </div>
    </nav>    
</head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>