jobhunt/urls.py
from django.urls import path
from . import views

app_name = 'jobhunt'

urlpatterns = [
    path('', views.job_list, name='job_list'),
    path('detail/<int:job_id>', views.job_detail, name='job_detail'),
    path('detail/<int:job_id>/create/', views.add_contact, name="add_contact"),
    path('detail/<int:job_id>/add/', views.add_activity, name="add_activity"),
    path('detail/add/',views.add_job, name='add_job'),
]

jobhuntpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobhunt.urls', namespace='jobhunt')),
    path('accounts/', include('accounts.urls')),
]

jobhunt/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Job(models.Model):
    class status_types(models.TextChoices):
        ACTIVE = 'AC', ('Active')
        NOTSELECTED = 'NS', ('Not Selected')
        WITHDRAWN = 'WD', ('Withdrawn')

    employer = models.CharField(max_length=100)
    job_title = models.CharField(max_length=100, blank=True)
    job_description = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    status = models.CharField(
        max_length=2,
        choices=status_types.choices,
        default=status_types.ACTIVE
    )
    job_application_url = models.TextField(blank=True)
    application_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.job_title}: {self.employer}'

    def get_status(self):
        return Job.status_types(self.status).label

class Contact(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=11)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.title}'



class Activity(models.Model):
    activity = models.CharField(max_length=50)
    date = models.DateTimeField()
    note = models.TextField()
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.activity} - {self.date}'

jobhunt/forms.py
from django import forms
from django.forms import ModelForm, TextInput, Textarea
from .models import Job, Contact, Activity


class AddContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'title', 'email', 'phone']
        labels = {
                    'name': ("Contact Name:"),
                    'title': ('Title:'),
                    'email': ('Email:'),
                    'phone': ('Phone No:'),
                }
        widgets = {
                    'name': TextInput(attrs={
                        'class': 'form-control',
                        'placeholder': 'John Smith',
                    }),
                    'title': TextInput(attrs={
                        'class': 'form-control',
                        'placeholder': 'HR Generalist',
                    }),
                    'email': TextInput(attrs={
                        'class': 'form-control',
                        'placeholder': 'jsmith@thiscompany.com'
                    }),
                    'phone': TextInput(attrs={
                        'class': 'form-control',
                        'placeholder': '512-459-2222'
                    })
        }
        


class AddJobForm(ModelForm):
    class Meta:
        model = Job
        fields = ['employer', 'job_title', 'job_description', 'notes', 'status']
        labels = { 'employer': ('Employer'),
                   'job_title': ('Job Title'),
                   'job_description': ('Job Description'),
                   'notes': ('Notes'),
                 }
        widgets = {
            'employer': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Employer'
                }),
            'job_title': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Job Title',
            }),
            'job_description': Textarea(attrs={
                'rows': 5
            }),
            'notes': Textarea(attrs={
                'rows': 3
            }),
        }



class AddActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = ['activity', 'date', 'note']
        labels = {
            'activity': ('Activity:'),
            'date': ('Date:'),
            'note': ('Note:'),
        }
        widgets = {
            'activity': TextInput(attrs={
                'class': 'form-control',
                'placeholder': '1st Interview',
            }),
            'date': TextInput(attrs={
                'class': 'form-control',
            }),
            'note': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Review company background',
            }),
        }

jobhunt/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Job, Contact, Activity
from .forms import AddContactForm, AddActivityForm, AddJobForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def job_list(request):
    jobs = Job.objects.filter(user=request.user)
    return render(request, 'jobhunt/pages/job_list.html', {'jobs': jobs})



def job_detail(request, job_id):
    job = get_object_or_404(Job, pk=job_id)
    activities = Activity.objects.filter(pk=job_id)
    contacts = Contact.objects.filter(pk=job_id)
    print(contacts)
    print(activities)
    return render(request, 'jobhunt/pages/job_detail.html', {
                    'job': job,
                    'activities': activities,
                    'contacts': contacts,
                 })



def add_contact(request, job_id):
    job = get_object_or_404(Job, pk=job_id)
    if request.method == 'GET':
        return render(request, 'jobhunt/pages/addcontactform.html',
                        {
                            'form': AddContactForm(),
                            'job': job
                        })
    else:
        try:
            name = request.POST['contact_name']
            title = request.POST['contact_title']
            email = request.POST['contact_email']
            phone = request.POST['contact_phone']
            job_id = job_id
            contact = Contact.objects.create(
                        name = name,
                        title = title,
                        email = email,
                        phone = phone,
                        job_id = job_id
            )
            return redirect('jobhunt:job_detail', job.id)
        except ValueError:
            return render(request, 'jobhunt/pages/addcontactform.html', {
                'form': AddContactForm(),
                'error': 'Bad data submitted'
            })



def add_activity(request, job_id):
    job = get_object_or_404(Job, pk=job_id)
    if request.method == 'GET':
        return render(request, 'jobhunt/pages/addactivityform.html',
                        {
                            'form': AddActivityForm(),
                            'job': job
                        })
    else:
        try:
            activity_name = request.POST['activity']
            date = request.POST['date']
            note = request.POST['note']
            job_id = job_id
            activity = Activity.objects.create(
                    activity = activity_name,
                    date = date,
                    note = note
            )
            return redirect('jobhunt:job_detail', job.id)
        except ValueError:
            return render(request, 'jobhunt/pages/addactivityform.html', {
                'form': AddActivityForm(),
                'error': 'Bad data submitted'
            })



@login_required
def add_job(request):
    if request.method == 'GET':
        return render(request, 'jobhunt/pages/add_job.html', {
                        'form': AddJobForm(),
                    })
    else:
        try:
            form = AddJobForm(request.POST)
            newJob = form.save(commit=False)
            newJob.user = request.user
            newJob.save()
            return redirect('jobhunt:job_detail', newJob.id)
        except ValueError:
            return render(request, 'jobhunt/pages/add_job.html', {
                            'form': AddJobForm(),
                            'error': 'bad data passed in'
                        })

jobhunt/templates/jobhunt/pages/add_job.html
{% extends 'base.html' %}
{% block content %}
    <div class="card mb-3">
        <div class="row g-0">
            <div>
                <div class="card-body">
                    <h5 class="card-title">Add New Job</h5>
                    {% if error %}
                        <div class="alert alert-danger mt-3" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                    <p class="card-text">
                        <form method='POST'>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn">
                                Add Activity
                            </button>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

jobhunt/templates/jobhunt/pages/addactivityform.html
{% extends 'base.html' %}
{% block content %}
    <div class="container col-4">
        <div class="card mb-3">
            <div class="row g-0">
                <div>
                    <div class="card-body">
                        <h5 class="card-title">Add Activity for {{ job.title }} at {{ job.employer }}</h5>
                        {% if error %}
                            <div class="alert alert-danger mt-3" role="alert">
                                {{ error }}
                            </div>
                        {% endif %}
                        <p class="card-text">
                            <form method='POST'>
                                {% csrf_token %}
                                {{ form.as_p }}
                            </form>
                            <div class="text-center">
                                <button type="submit" class="btn text-center">
                                    Add Activity
                                </button>
                            </div>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

jobhunt/templates/jobhunt/pages/addcontactform.html
{% extends 'base.html' %}
{% block content %}
    <div class="container col-4">
        <div class="card mb-3">
            <div class="row g-0">
                <div>
                    <div class="card-body">
                        <h5 class="card-title">Add Contact for {{ job.title }} at {{ job.employer }}</h5>
                        {% if error %}
                            <div class="alert alert-danger mt-3" role="alert">
                                {{ error }}
                            </div>
                        {% endif %}
                        <p class="card-text">
                            <form method='POST'>
                                {% csrf_token %}
                                {{ form.as_p }}
                            </form>
                            <div class="text-center">
                                <button type="submit" class="btn text-center">
                                    Add Contact
                                </button>
                            </div>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

jobhunt/templates/jobhunt/pages/job_detail.html
{% extends "base.html"  %}

{% block title %}Job Hunt Pro{% endblock title %}

{% block content %}
    <h1 class="my-3 text-center">Job Hunt Pro</h1>
    <div class="container text-light">
        <div class="container-fluid p-3 my-3 rounded">
            <h5>Job Title: {{ job.job_title }}</h5>
            <h6>Employer: {{ job.employer }}
            <p>Application Submitted: {{ job.application_date }}
            <p><strong>Job Description:</strong></p>
            <p>{{ job.job_description|linebreaks }}</p>
            {% if job.notes %}
                <p><strong>Notes</strong></p>
                <p>{{ job.notes|linebreaks }}</p>
            {% endif %}
            <p class='card-text'>
                Job Status: {{ job.get_status }}
            </p>
            <div class=text-center>
                <a href="#" class="btn">
                    Update Job
                </a>
                <a href="#" class="btn">
                    Delete Job
                </a>
                <a href="{% url 'jobhunt:add_activity' job.id %}" class="btn">
                    Add Activity
                </a>
                <a href="{% url 'jobhunt:add_contact' job.id %}" class="btn">
                    Add Contact
                </a>
            </div>
        </div>
    </div>
{% endblock %}

jobhunt/templates/jobhunt/pages/job_list.html
{% extends "base.html"  %}

{% block title %}Job Hunt Pro{% endblock title %}

{% block content %}
    <h1 class="mb-5 text-center">Job Hunt Pro</h1>
        <div class="container">
        {% if not jobs  %}
            <div class='text-center'>
                <h5>You currently have no jobs listed.</h5>
            </div>
        {% else %}
            <div class="row g-0">
                {% for job in jobs %}
                    <div class="col-3 mx-2">
                        <a href="{% url "jobhunt:job_detail" job.id %}" class="text-decoration-none">
                            <div class="card card-expand mb-3 rounded shadow-lg text-light">
                                <div class="card-body text-center">
                                    <h3>{{ job.job_title }}</h3>
                                    <h4>{{ job.employer }}</h4>
                                    <h5>Applied: {{ job.application_date }}</h5>
                                    <p class='card-text'>
                                        {{ job.job_description|truncatewords:30|linebreaks }}
                                    </p>
                                    <p class='card-text'>
                                        {{ job.get_status }}
                                    </p>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="text-center pt-3">
            <a href="{% url 'jobhunt:add_job' %}" class="btn">Add Job</a>
        </div>
    </div>
{% endblock %}